[package]
name = "minigrep"
version = "0.1.0"
edition = "2021"
description = "A command-line utility for searching plain-text data sets for lines"
license = "MIT OR Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
